CREATE TABLE `exam_tk_uy` (
  `STXH` varchar(6) NOT NULL,
  `BH` varchar(15) DEFAULT NULL,
  `STLX` varchar(3) NOT NULL,
  `STSX` char(1) NOT NULL,
  `STTX` char(1) NOT NULL,
  `STNR` text,
  `XZDAA` text,
  `XZDAB` text,
  `XZDAC` text,
  `XZDAD` text,
  `TXLJ` varchar(128) DEFAULT NULL,
  `STDA` varchar(4) DEFAULT NULL,
  `STBJ` char(1) DEFAULT NULL,
  `BZ` varchar(128) DEFAULT NULL,
  `SYCX` varchar(32) DEFAULT NULL,
  `TK1BH` varchar(10) DEFAULT NULL,
  `TK2BH` varchar(10) DEFAULT NULL,
  `PROV` varchar(2) DEFAULT NULL,
  `GXSJ` datetime DEFAULT NULL,
  `STFL` varchar(2) DEFAULT NULL,
  `TKLX` varchar(6) DEFAULT NULL,
  `KSYY` varchar(6) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `exam_tk_mon` (
  `STXH` varchar(6) NOT NULL,
  `BH` varchar(15) DEFAULT NULL,
  `STLX` varchar(3) NOT NULL,
  `STSX` char(1) NOT NULL,
  `STTX` char(1) NOT NULL,
  `STNR` text,
  `XZDAA` text,
  `XZDAB` text,
  `XZDAC` text,
  `XZDAD` text,
  `TXLJ` varchar(128) DEFAULT NULL,
  `STDA` varchar(4) DEFAULT NULL,
  `STBJ` char(1) DEFAULT NULL,
  `BZ` varchar(128) DEFAULT NULL,
  `SYCX` varchar(32) DEFAULT NULL,
  `TK1BH` varchar(10) DEFAULT NULL,
  `TK2BH` varchar(10) DEFAULT NULL,
  `PROV` varchar(2) DEFAULT NULL,
  `GXSJ` datetime DEFAULT NULL,
  `STFL` varchar(2) DEFAULT NULL,
  `TKLX` varchar(6) DEFAULT NULL,
  `KSYY` varchar(6) DEFAULT NULL,
  PRIMARY KEY (`STXH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `exam_tk_ha` (
  `STXH` varchar(6) NOT NULL,
  `BH` varchar(15) DEFAULT NULL,
  `STLX` varchar(3) NOT NULL,
  `STSX` char(1) NOT NULL,
  `STTX` char(1) NOT NULL,
  `STNR` text,
  `XZDAA` text,
  `XZDAB` text,
  `XZDAC` text,
  `XZDAD` text,
  `TXLJ` varchar(128) DEFAULT NULL,
  `STDA` varchar(4) DEFAULT NULL,
  `STBJ` char(1) DEFAULT NULL,
  `SYCX` varchar(32) DEFAULT NULL,
  `TK1BH` varchar(10) DEFAULT NULL,
  `TK2BH` varchar(10) DEFAULT NULL,
  `PROV` varchar(2) DEFAULT NULL,
  `JYW` text,
  `GXSJ` datetime DEFAULT NULL,
  `STFL` varchar(2) DEFAULT NULL,
  `TKLX` varchar(6) DEFAULT NULL,
  `KSYY` varchar(6) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `exam_tk_cn` (
  `STXH` varchar(6) NOT NULL,
  `BH` varchar(15) NOT NULL,
  `STLX` varchar(3) NOT NULL,
  `STSX` varchar(1) NOT NULL,
  `STTX` varchar(1) NOT NULL,
  `STNR` text,
  `XZDAA` text,
  `XZDAB` text,
  `XZDAC` text,
  `XZDAD` text,
  `TXLJ` varchar(128) DEFAULT NULL,
  `STDA` varchar(4) NOT NULL,
  `STBJ` varchar(1) DEFAULT NULL,
  `SYCX` varchar(32) NOT NULL,
  `TK1BH` varchar(10) DEFAULT NULL,
  `TK2BH` varchar(10) DEFAULT NULL,
  `PROV` varchar(2) DEFAULT NULL,
  `JYW` text,
  `GXSJ` datetime DEFAULT NULL,
  `STFL` varchar(3) DEFAULT NULL,
  `TKLX` varchar(6) DEFAULT NULL,
  `KSYY` varchar(6) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;